package com.giraffe.matn.teacher.presentation.strings

object ArabicStrings : TeacherStrings {
    override val appName = "متن"
    override val navDashboard = "لوحة التحكم"
    override val navUploadMatn = "رفع متن"
    override val navLibraryManagement = "إدارة المكتبة"
    override val navSystemSettings = "إعدادات النظام"
    override val teacherPortalLabel = "بوابة المعلم"
    override val storageUsageLabel = "مساحة التخزين"
    override val storageUsageFormat = "%s من %s مستخدمة"
    override val signOut = "تسجيل الخروج"
    override val languageSwitch = "English"
    override val secretStoreUnprotectedWarning =
        "تعذّر حفظ جلستك بشكل آمن على هذا الجهاز. سجّل الدخول مجددًا في المرة القادمة."
    override val screenNotYetAvailable = "هذه الشاشة غير متوفرة في هذا الإصدار بعد."

    override val signInTitle = "تسجيل الدخول إلى متن"
    override val emailLabel = "البريد الإلكتروني"
    override val passwordLabel = "كلمة المرور"
    override val signInButton = "تسجيل الدخول"
    override val signingIn = "جارٍ تسجيل الدخول…"

    override val libraryEmptyTitle = "لا توجد متون بعد"
    override val libraryEmptyAction = "أنشئ أول متن"
    override val libraryLoading = "جارٍ تحميل مكتبتك…"
    override val libraryRetry = "إعادة المحاولة"
    override val publicationStatusDraft = "مسودة"
    override val publicationStatusPublished = "منشور"
    override val audioCompletenessNone = "بلا صوت"
    override val audioCompletenessPartial = "صوت جزئي"
    override val audioCompletenessComplete = "صوت مكتمل"

    override val uploadNewMatnHeading = "رفع متن جديد"
    override val uploadNewMatnLead =
        "أنشئ نصًا منظّمًا للحفظ. يمكن ربط كل بيت بتسجيل صوتي عالي الجودة خاص به لتكرار دقيق من الطالب."
    override val generalInformationHeading = "معلومات عامة"
    override val matnTitleLabel = "عنوان المتن"
    override val matnTitlePlaceholder = "مثال: الجزرية في التجويد"
    override val authorLabel = "المؤلف / الشيخ"
    override val authorPlaceholder = "ابن الجزري"
    override val descriptionLabel = "وصف مختصر"
    override val descriptionPlaceholder = "سياق موجز عن هذا النص للطلاب…"
    override val coverArtLabel = "صورة الغلاف"
    override val coverArtHint = "المقاس المُوصى به: 800 × 1200 بكسل"
    override val coverArtRemove = "إزالة الغلاف"
    override val proTipHeading = "نصيحة"
    override val proTipBody = "تقسيم الصوت حسب البيت يساعد الطلاب على الاستفادة من ميزة 'التكرار التلقائي' بفعالية أكبر."
    override val structureKindLabel = "البنية"
    override val structureKindSimple = "بسيطة"
    override val structureKindStructured = "منظمة (بفصول)"
    override val chaptersHeading = "الفصول"
    override val addChapter = "إضافة فصل"

    override val verseListHeading = "قائمة الأبيات"
    override val bulkImport = "استيراد جماعي"
    override val addVerse = "إضافة بيت"
    override val addNextVerse = "إضافة البيت التالي"
    override val deleteVerse = "حذف البيت"
    override val moveVerseUp = "نقل البيت لأعلى"
    override val moveVerseDown = "نقل البيت لأسفل"
    override val dragToReorder = "اسحب لإعادة الترتيب"
    override val assignChapter = "الفصل"
    override val clearAllVerses = "حذف الكل"
    override val clearAllVersesConfirmTitle = "حذف جميع الأبيات؟"
    override val clearAllVersesConfirmBody = "سيؤدي هذا إلى حذف جميع الأبيات الحالية في القائمة. لا يمكن التراجع عن هذا الإجراء."
    override val clearAllVersesConfirmAction = "حذف الكل"

    override val saveAsDraft = "حفظ كمسودة"
    override val publishMatn = "نشر المتن"
    override val unpublishMatn = "إلغاء النشر"
    override val checkForProblems = "فحص"
    override val saveStateIdle = "لم يُحفظ بعد"
    override val saveStateAutosaving = "جارٍ الحفظ…"
    override val saveStateSavedAt = "تم الحفظ %s"
    override val saveStateFailed = "فشل الحفظ"
    override val publishedEditingBanner = "هذا المتن منشور — تظهر التغييرات فور الحفظ."

    override val publishConfirmTitle = "نشر هذا المتن؟"
    override val publishConfirmBody = "سيُنشر دون تسجيلات صوتية حتى الآن."
    override val publishConfirmAction = "نشر"
    override val unpublishConfirmTitle = "إلغاء نشر هذا المتن؟"
    override val unpublishConfirmBody = "لن يراه الطلاب بعد الآن. يمكنك إعادة نشره دون تغيير في أي وقت."
    override val unpublishConfirmAction = "إلغاء النشر"
    override val cancelAction = "إلغاء"

    override val validationBlockingHeading = "يجب إصلاحه قبل النشر"
    override val validationDeferredHeading = "لا يزال معلّقًا"

    override val importPreviewTitle = "استيراد الأبيات"
    override val importPreviewLineCount = "%d سطرًا"
    override val importPreviewProblemLine = "تعذّرت قراءة السطر %d"
    override val importCancel = "إلغاء"
    override val importConfirm = "استيراد"
    override val importInvalidEncodingError = "هذا الملف ليس نصًا بترميز UTF-8 عاديًا — يُرجى تصديره بترميز UTF-8 والمحاولة مجددًا."

    override val errorNetworkMessage = "تعذّر الوصول إلى الخادم."
    override val errorNetworkAction = "إعادة المحاولة"
    override val errorUnauthorizedMessage = "انتهت الجلسة — سجّل الدخول مجددًا."
    override val errorUnauthorizedAction = "تسجيل الدخول مجددًا"
    override val errorForbiddenMessage = "لا يمكن لهذا الحساب تعديل المحتوى."
    override val errorConflictMessage = "تم تغييره في مكان آخر منذ فتحه."
    override val errorConflictAction = "إعادة التحميل"
    override val errorQuotaExceededMessage = "مساحة التخزين ممتلئة. احذف بعض المحتوى وحاول مجددًا."
    override val errorServerMessage = "مشكلة في الخادم. حاول مجددًا."
    override val errorServerAction = "إعادة المحاولة"
    override val errorDecodeMessage = "استجابة غير متوقعة — يُرجى الإبلاغ عن هذا."

    override val validationInvalidId = "مشكلة داخلية في %s — يُرجى الإبلاغ عن هذا"
    override val validationDuplicateId = "يشترك عنصران في نفس المعرّف — احذف اللاحق وأعد إضافته"
    override val validationDuplicateDisplayNumber = "يشترك بيتان في الرقم %s"
    override val validationDuplicateChapterOrder = "يقع الفصلان %s في نفس الموضع"
    override val validationMissingAudio = "لا يوجد تسجيل صوتي للبيت %s بعد"
    override val validationDuplicateAudioRef = "تشير الأبيات %s إلى نفس التسجيل"
    override val validationOrphanChapterRef = "ينتمي البيت %s إلى فصل لم يعد موجودًا"
    override val validationEmptyMatn = "لا يحتوي هذا المتن على أبيات بعد"
    override val validationDocumentTooLarge = "هذا المتن أكبر من أن يُنشر — %s من %s المسموح بها"
}
