package com.giraffe.matn.teacher.presentation.strings

object EnglishStrings : TeacherStrings {
    override val appName = "Matn"
    override val navDashboard = "Dashboard"
    override val navUploadMatn = "Upload Matn"
    override val navLibraryManagement = "Library Management"
    override val navSystemSettings = "System Settings"
    override val teacherPortalLabel = "Teacher Portal"
    override val storageUsageLabel = "Storage Usage"
    override val storageUsageFormat = "%s of %s used"
    override val signOut = "Sign Out"
    override val languageSwitch = "العربية"
    override val secretStoreUnprotectedWarning =
        "Your session could not be stored securely on this device. Sign in again next time you open the app."

    override val signInTitle = "Sign in to Matn"
    override val emailLabel = "Email"
    override val passwordLabel = "Password"
    override val signInButton = "Sign In"
    override val signingIn = "Signing in…"

    override val libraryEmptyTitle = "No matns yet"
    override val libraryEmptyAction = "Create your first matn"
    override val libraryLoading = "Loading your library…"
    override val libraryRetry = "Retry"
    override val publicationStatusDraft = "Draft"
    override val publicationStatusPublished = "Published"
    override val audioCompletenessNone = "No audio"
    override val audioCompletenessPartial = "Partial audio"
    override val audioCompletenessComplete = "Audio complete"

    override val uploadNewMatnHeading = "Upload New Matn"
    override val uploadNewMatnLead =
        "Create a structured memorization text. Each verse can be paired with its own high-quality audio recording for precise student repetition."
    override val generalInformationHeading = "General Information"
    override val matnTitleLabel = "Matn Title"
    override val matnTitlePlaceholder = "e.g. Al-Jazariyyah in Tajweed"
    override val authorLabel = "Author / Scholar"
    override val authorPlaceholder = "Ibn al-Jazari"
    override val descriptionLabel = "Short Description"
    override val descriptionPlaceholder = "Brief context about this text for the students…"
    override val coverArtLabel = "Cover Art"
    override val coverArtHint = "Recommended size: 800 x 1200 px"
    override val coverArtRemove = "Remove cover"
    override val proTipHeading = "Pro-Tip"
    override val proTipBody =
        "Splitting audio by verse helps students utilize the 'Auto-Repeat' feature more effectively."
    override val structureKindLabel = "Structure"
    override val structureKindSimple = "Simple"
    override val structureKindStructured = "Structured (with chapters)"
    override val chaptersHeading = "Chapters"
    override val addChapter = "Add Chapter"

    override val verseListHeading = "Verse List"
    override val bulkImport = "Bulk Import"
    override val addVerse = "Add Verse"
    override val addNextVerse = "Add Next Verse"
    override val deleteVerse = "Delete verse"
    override val moveVerseUp = "Move verse up"
    override val moveVerseDown = "Move verse down"
    override val dragToReorder = "Drag to reorder"
    override val assignChapter = "Chapter"

    override val saveAsDraft = "Save as Draft"
    override val publishMatn = "Publish Matn"
    override val unpublishMatn = "Unpublish"
    override val checkForProblems = "Check"
    override val saveStateIdle = "Not saved yet"
    override val saveStateAutosaving = "Saving…"
    override val saveStateSavedAt = "Saved %s"
    override val saveStateFailed = "Save failed"
    override val publishedEditingBanner = "This matn is published — changes go live as soon as you save."

    override val publishConfirmTitle = "Publish this matn?"
    override val publishConfirmBody = "It will be published with no recordings yet."
    override val publishConfirmAction = "Publish"
    override val unpublishConfirmTitle = "Unpublish this matn?"
    override val unpublishConfirmBody = "Students will no longer see it. You can republish it unchanged at any time."
    override val unpublishConfirmAction = "Unpublish"
    override val cancelAction = "Cancel"

    override val validationBlockingHeading = "Must fix before publishing"
    override val validationDeferredHeading = "Still outstanding"

    override val importPreviewTitle = "Import Verses"
    override val importPreviewLineCount = "%d lines"
    override val importPreviewProblemLine = "Line %d could not be read"
    override val importCancel = "Cancel"
    override val importConfirm = "Import"
    override val importInvalidEncodingError = "This file is not plain UTF-8 text — please export it as UTF-8 and try again."

    override val errorNetworkMessage = "Cannot reach the server."
    override val errorNetworkAction = "Retry"
    override val errorUnauthorizedMessage = "Session ended — sign in again."
    override val errorUnauthorizedAction = "Sign in again"
    override val errorForbiddenMessage = "This account cannot change content."
    override val errorConflictMessage = "Changed elsewhere since you opened it."
    override val errorConflictAction = "Reload"
    override val errorQuotaExceededMessage = "Storage is full. Remove some content and try again."
    override val errorServerMessage = "Server problem. Please try again."
    override val errorServerAction = "Retry"
    override val errorDecodeMessage = "Unexpected response — please report this."

    override val validationInvalidId = "Internal problem with %s — report this"
    override val validationDuplicateId = "Two entries share an identifier — remove and re-add the later one"
    override val validationDuplicateDisplayNumber = "Two verses share the number %s"
    override val validationDuplicateChapterOrder = "Chapters %s are at the same position"
    override val validationMissingAudio = "Verse %s has no recording yet"
    override val validationDuplicateAudioRef = "Verses %s point at the same recording"
    override val validationOrphanChapterRef = "Verse %s belongs to a chapter that no longer exists"
    override val validationEmptyMatn = "This matn has no verses yet"
    override val validationDocumentTooLarge = "This matn is too large to publish — %s of %s allowed"
}
