package com.giraffe.matn.teacher.presentation.strings

object EnglishStrings : TeacherStrings {
    override val appName = "Matn"
    override val navDashboard = "Dashboard"
    override val navUploadMatn = "Upload Matn"
    override val navLibraryManagement = "Library Management"
    override val navSystemSettings = "System Settings"
    override val teacherPortalLabel = "Teacher Portal"
    override val storageUsageLabel = "Storage Usage"
    override val storageUsageFormat = "%s of %s used"
    override val signOut = "Sign Out"
    override val languageSwitch = "العربية"
    override val secretStoreUnprotectedWarning =
        "Your session could not be stored securely on this device. Sign in again next time you open the app."
    override val screenNotYetAvailable = "This screen isn't available in this version yet."

    override val signInTitle = "Sign in to Matn"
    override val emailLabel = "Email"
    override val passwordLabel = "Password"
    override val signInButton = "Sign In"
    override val signingIn = "Signing in…"

    override val libraryEmptyTitle = "No matns yet"
    override val libraryEmptyAction = "Create your first matn"
    override val libraryLoading = "Loading your library…"
    override val libraryRetry = "Retry"
    override val publicationStatusDraft = "Draft"
    override val publicationStatusPublished = "Published"
    override val audioCompletenessNone = "No audio"
    override val audioCompletenessPartial = "Partial audio"
    override val audioCompletenessPartialCount = "%d of %d recorded"
    override val audioCompletenessComplete = "Audio complete"

    override val uploadNewMatnHeading = "Upload New Matn"
    override val uploadNewMatnLead =
        "Create a structured memorization text. Each verse can be paired with its own high-quality audio recording for precise student repetition."
    override val generalInformationHeading = "General Information"
    override val matnTitleLabel = "Matn Title"
    override val matnTitlePlaceholder = "e.g. Al-Jazariyyah in Tajweed"
    override val authorLabel = "Author / Scholar"
    override val authorPlaceholder = "Ibn al-Jazari"
    override val descriptionLabel = "Short Description"
    override val descriptionPlaceholder = "Brief context about this text for the students…"
    override val coverArtLabel = "Cover Art"
    override val coverArtHint = "Recommended size: 800 x 1200 px"
    override val coverArtRemove = "Remove cover"
    override val coverUploadFailedError = "Cover upload failed. Try again."
    override val coverInvalidFileError = "Invalid file. Choose a PNG, JPEG, or WebP image under 5 MB."
    override val proTipHeading = "Pro-Tip"
    override val proTipBody =
        "Splitting audio by verse helps students utilize the 'Auto-Repeat' feature more effectively."
    override val structureKindLabel = "Structure"
    override val structureKindSimple = "Simple"
    override val structureKindStructured = "Structured (with chapters)"
    override val chaptersHeading = "Chapters"
    override val chapterTitleLabel = "Chapter title"
    override val chapterStartsAtVerse = "Starts at verse"
    override val deleteChapter = "Delete chapter"
    override val addChapter = "Add Chapter"

    override val verseListHeading = "Verse List"
    override val bulkImport = "Bulk Import"
    override val addVerse = "Add Verse"
    override val addNextVerse = "Add Next Verse"
    override val deleteVerse = "Delete verse"
    override val moveVerseUp = "Move verse up"
    override val moveVerseDown = "Move verse down"
    override val dragToReorder = "Drag to reorder"
    override val assignChapter = "Chapter"
    override val clearAllVerses = "Clear All"
    override val clearAllVersesConfirmTitle = "Delete every verse?"
    override val clearAllVersesConfirmBody = "This removes all verses currently in the list. This cannot be undone."
    override val clearAllVersesConfirmAction = "Delete All"

    override val saveAsDraft = "Save as Draft"
    override val publishMatn = "Publish Matn"
    override val unpublishMatn = "Unpublish"
    override val checkForProblems = "Check"
    override val saveStateIdle = "Not saved yet"
    override val saveStateAutosaving = "Saving…"
    override val saveStateSavedAt = "Saved %s"
    override val saveStateFailed = "Save failed"
    override val publishedEditingBanner = "This matn is published — changes go live as soon as you save."

    override val publishConfirmTitle = "Publish this matn?"
    override val publishConfirmBody = "This matn will become available to students with all of its recordings."
    override val publishConfirmVerseCount = "%d verses"
    override val publishConfirmAction = "Publish"
    override val unpublishConfirmTitle = "Unpublish this matn?"
    override val unpublishConfirmBody = "Students will no longer see it. You can republish it unchanged at any time."
    override val unpublishConfirmAction = "Unpublish"
    override val cancelAction = "Cancel"

    override val validationBlockingHeading = "Must fix before publishing"
    override val validationDeferredHeading = "Still outstanding"

    override val importPreviewTitle = "Import Verses"
    override val importPreviewLineCount = "%d lines"
    override val importPreviewProblemLine = "Line %d could not be read"
    override val importCancel = "Cancel"
    override val importConfirm = "Import"
    override val importInvalidEncodingError = "This file is not plain UTF-8 text — please export it as UTF-8 and try again."

    override val errorNetworkMessage = "Cannot reach the server."
    override val errorNetworkAction = "Retry"
    override val errorUnauthorizedMessage = "Session ended — sign in again."
    override val errorUnauthorizedAction = "Sign in again"
    override val errorForbiddenMessage = "This account cannot change content."
    override val errorConflictMessage = "Changed elsewhere since you opened it."
    override val errorConflictAction = "Reload"
    override val errorQuotaExceededMessage = "Storage is full. Remove some content and try again."
    override val errorServerMessage = "Server problem. Please try again."
    override val errorServerAction = "Retry"
    override val errorRejectedMessage = "The server refused this content — its type or size isn't allowed."
    override val errorDecodeMessage = "Unexpected response — please report this."

    override val addRecording = "Add recording"
    override val replaceRecording = "Replace recording"
    override val removeRecording = "Remove recording"
    override val playRecording = "Play"
    override val uploadingAudio = "Uploading…"
    override val audioProfileMismatch = "This matn's audio is %s; this file is %s"
    override val audioTooLarge = "This recording is larger than the 10 MB per-verse limit"
    override val audioWrongFormat = "This file could not be read as MP3"
    override val audioUnreadable = "This recording could not be played"
    override val storageFull = "Storage is full — remove some content and try again"

    override val splitFromRecording = "Split from one recording"
    override val pickRecording = "Pick a recording"
    override val replaceSourceRecording = "Replace source recording"
    override val scopeFirstVerse = "First verse"
    override val scopeLastVerse = "Last verse"
    override val rangeStart = "Start (ms)"
    override val rangeEnd = "End (ms)"
    override val nudgeEarlier = "%d ms earlier"
    override val nudgeLater = "%d ms later"
    override val splitAndUpload = "Split and upload"
    override val splitSourceHint = "Pick one MP3 recording covering several verses — up to 300 MB and 4 hours."
    override val splitLoadingSource = "Analysing the recording… this can take a minute for a long one."
    override val splitUploading = "Splitting and uploading…"
    override val auditionRange = "Listen to this clip"
    override val stopAudition = "Stop"
    override val playSource = "Play recording"
    override val pauseSource = "Stop recording"
    override val scrubHintIdle = "Drag the waveform to move the playhead. Focus a verse's Start or End field to place that boundary."
    override val scrubHintArmed = "Dragging sets verse %s — %s. Use the top strip to move the playhead."
    override val splitRangedCount = "%d of %d verses ranged"
    override val splitProblemsMore = "+%d more"
    override val sourceTooLong = "This recording is longer than the 4 hour limit"
    override val sourceTooLarge = "This recording is larger than the 300 MB limit"
    override val splitProblemMissingRange = "Verse %s has no range yet"
    override val splitProblemInvertedRange = "Verse %s's range ends before it starts"
    override val splitProblemTooShort = "Verse %s's range is shorter than 300 ms"
    override val splitProblemOutOfBounds = "Verse %s's range is outside the recording (%s)"
    override val splitProblemOverlap = "Verses %s and %s overlap"
    override val splitProblemRangeOutOfScope = "Verse %s is outside the current scope"
    override val splitProblemUncoveredStretch = "No verse covers %s to %s"

    override val previewMatn = "Preview matn"
    override val previewPlaying = "Playing verse %s"
    override val previewPaused = "Paused at verse %s"
    override val previewMissingAudio = "Verse %s has no recording"
    override val previewBuffering = "Loading…"

    override val validationInvalidId = "Internal problem with %s — report this"
    override val validationDuplicateId = "Two entries share an identifier — remove and re-add the later one"
    override val validationDuplicateDisplayNumber = "Two verses share the number %s"
    override val validationDuplicateChapterOrder = "Chapters %s are at the same position"
    override val validationMissingAudio = "Verse %s has no recording yet"
    override val validationDuplicateAudioRef = "Verses %s point at the same recording"
    override val validationOrphanChapterRef = "Verse %s belongs to a chapter that no longer exists"
    override val validationEmptyMatn = "This matn has no verses yet"
    override val validationDocumentTooLarge = "This matn is too large to publish — %s of %s allowed"
}
